# Generated by Django 3.2.4 on 2021-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('page_count', models.IntegerField()),
                ('thumbnail_url', models.CharField(max_length=256)),
                ('short_description', models.CharField(max_length=256)),
            ],
        ),
    ]
