# Generated by Django 3.2.4 on 2021-07-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210630_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='long_description',
            new_name='longDescription',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page_count',
            new_name='pageCount',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='short_description',
            new_name='shortDescription',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='thumbnail_url',
            new_name='thumbnailUrl',
        ),
    ]
